[project]
name = "belgie"
version = "0.1.0"
description = "Modern authentication for FastAPI"
readme = "README.md"
authors = [
    { name = "Matt LeMay", email = "mplemay@users.noreply.github.com" }
]
requires-python = ">=3.12,<3.15"
dependencies = [
    "fastapi>=0.100",
    "httpx>=0.24",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
    "python-multipart>=0.0.20",
    "sqlalchemy[asyncio]>=2.0",
]

[project.optional-dependencies]
examples = [
    "uvicorn[standard]>=0.38.0",
]

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "pre-commit>=4.4.0",
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "respx>=0.22.0",
    "ruff>=0.14.5",
    "ty>=0.0.1a27",
]

[tool.ruff]
target-version = "py312"
line-length = 120
include = ["pyproject.toml"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D", # pydocstyle (i.e. ignore missing/malformed docstrings)
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401", # imported but unused (common in __init__.py to re-export symbols)
]
"__tests__/**/*" = [
    "S101",    # use of assert (tests typically use assert directly)
    "PLR2004", # magic value used in comparison (fine in test cases)
    "INP001",  # implicit namespace package (tests dir may not need __init__.py)
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

[tool.pytest.ini_options]
asyncio_mode = "strict"
