[package]
name = "view"
version = "0.1.0"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "abi3-py312"] }
tokio = { version = "1.48.0", features = ["full"] }
deno_core = { git = "https://github.com/denoland/deno_core", branch = "main" }
pyo3-async-runtimes = { version = "0.27", features = ["tokio-runtime"] }
once_cell = "1"
