[project]
name = "belgie-core"
version = "0.1.0"
description = "Core authentication logic for Belgie"
readme = "README.md"
authors = [
    { name = "Matt LeMay", email = "mplemay@users.noreply.github.com" }
]
requires-python = ">=3.12,<3.15"
dependencies = [
    "belgie-proto",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-exclude = ["**/__tests__/**"]
